EMarket/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EMarket.Data;
using EMarket.Models;
using EMarket.Helper;
using PagedList.Core;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace EMarket.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly dbMarketsContext _context;

        public AdminCategoriesController(dbMarketsContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page < 0 ? 1 : page.Value;
            var pageSize = Utilities.PAGE_SIZE;
            var lstPage = _context.Categories
                                       .AsNoTracking()
                                       .OrderByDescending(c => c.CatId);
            PagedList<Category> models = new PagedList<Category>(lstPage, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(category.CatName) + extension;
                    category.Thumb = await Utilities.UploadFile(fThumb, @"categories", image.ToLower());
                }

                if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                category.Alias = Utilities.SEOUrl(category.CatName);
                //category.CreatedDate = DateTime.Now;

                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CatId,CatName,Description,ParentId,Levels,Ordering,Published,Thumb,Title,Alias,MetaDesc,MetaKey,Cover,SchemaMarkup")] Category category, IFormFile fThumb)
        {
            if (id != category.CatId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    category.CatName = Utilities.ToTitleCase(category.CatName);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(category.CatName) + extension;
                        category.Thumb = await Utilities.UploadFile(fThumb, @"categories", image.ToLower());
                    }

                    if (string.IsNullOrEmpty(category.Thumb)) category.Thumb = "default.jpg";
                    category.Alias = Utilities.SEOUrl(category.CatName);
                    //category.CreatedDate = DateTime.Now;

                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CatId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CatId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            _context.Categories.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CatId == id);
        }
    }
}

EMarket/Areas/Admin/Views/AdminCategories/Create.cshtml
@model EMarket.Models.Category

@{
    ViewData["Title"] = "Thêm mới danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-success" type="submit">
                    <i class="anticon anticon-save"></i>
                    <span>Thêm</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="CatName">@Html.DisplayNameFor(Model => Model.CatName)</label>
                        <input type="text" class="form-control" asp-for="CatName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Ordering">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Ảnh đại diện</label>
                        <input type="file" name="fThumb" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" checked="">
                                    <label for="Published"></label>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea asp-for="Description">
                    </textarea>
                </div>
            </div>
        </div>
    </div>
</form>
<hr />

@section CSS{
    <style>
        .ck.ck-editor__main > .ck-editor__editable {
            min-height: 200px !important;
        }
    </style>
}

@section Scripts{

    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/Adminassets/vendors/ckeditor/build/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Description'), {
                licenseKey: '',
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                console.warn('Build id: mxefwd8uabpg-nvqywtx4rvf5');
                console.error(error);
            });
    </script>
}

EMarket/Areas/Admin/Views/AdminCategories/Delete.cshtml
@model EMarket.Models.Category


@{
    ViewData["Title"] = "Xóa Danh mục " + Model.CatId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    ViewBag.PageController = "AdminCategories";
    ViewBag.PageAction = "Index";
    ViewBag.PageControllerName = "Quản lý danh mục";
    ViewBag.PageActionName = "Chi tiết";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="@ViewBag.PageController" asp-action="Index">@ViewBag.PageControllerName</a>
            <a asp-area="Admin" asp-controller="@ViewBag.PageController" asp-action="@ViewBag.PageAction"><span class="breadcrumb-item active"> > @ViewBag.PageActionName</span></a>
        </nav>
    </div>
</div>
<h2 class="mb-4">Xóa Danh mục</h2>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="product-info-table m-t-20">
                        <tbody>
                            <tr>
                                <td class="text-dark font-weight-semibold">@Html.DisplayNameFor(model => model.CatId)</td>
                                <td>
                                    @Html.DisplayFor(model => model.CatId)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">@Html.DisplayNameFor(model => model.CatName)</td>
                                <td>
                                    @Html.DisplayFor(model => model.CatName)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">Public</td>
                                <td>
                                    @if (Model.Published)
                                    {
                                        <div class="switch m-r-10">
                                            <input type="checkbox" id="switch-1" checked="" disabled="">
                                            <label for="switch-1"></label>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="switch m-r-10">
                                            <input type="checkbox" id="switch-2" disabled="">
                                            <label for="switch-2"></label>
                                        </div>
                                    }
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">Alias</td>
                                <td>
                                    @Html.DisplayFor(model => model.Alias)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">Tiêu đề</td>
                                <td>
                                    @Html.DisplayFor(model => model.Title)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">MetaDesc</td>
                                <td>
                                    @Html.DisplayFor(model => model.MetaDesc)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">MetaKey</td>
                                <td>
                                    @Html.DisplayFor(model => model.MetaKey)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">Orderding</td>
                                <td>
                                    @Html.DisplayFor(model => model.Ordering)
                                </td>
                            </tr>
                            <tr>
                                <td class="text-dark font-weight-semibold">Ảnh đại diện</td>
                                <td>
                                    <img width="200" height="200" src="~/images/news/@Model.Thumb" alt="@Model.Title" />
                                </td>
                            </tr>

                        </tbody>
                    </table>
                    <div class="mt-1">
                        <h5 class="text-dark font-weight-semibold">Mô tả</h5>
                        <div class="mt-2">
                            <textarea asp-for="Description">
                                    </textarea>
                        </div>
                    </div>
                    <div class="mt-5">
                        <div class="row col-sm-12 col-md-6">
                            <div>
                                <span class="text-danger" style="font-size: 20px;">Xác nhận xóa ?</span>
                            </div>
                            <div class="ml-4">
                                <form asp-action="Delete" asp-route-id="@Model.CatId">
                                    <input type="hidden" asp-for="CatId" />
                                    <input type="submit" value="Xóa" class="btn btn-danger" />
                                </form>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="mt-4">
    <a asp-action="Index">&nbsp;< Quay lại</a>
</div>

@section CSS{
    <style>
        .ck.ck-editor__main > .ck-editor__editable {
            min-height: 200px !important;
        }
    </style>
}

@section Scripts{

    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/Adminassets/vendors/ckeditor/build/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Description'), {
                licenseKey: '',

            })
            .then(editor => {
                window.editor = editor;

                editor.isReadOnly = true;
            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                console.warn('Build id: mxefwd8uabpg-nvqywtx4rvf5');
                console.error(error);
            });
    </script>
}

EMarket/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model EMarket.Models.Category

@{
    ViewData["Title"] = "Chỉnh sửa danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CatId" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="CatId" />
    <input type="hidden" asp-for="Thumb" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-success" type="submit">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="CatName">@Html.DisplayNameFor(Model => Model.CatName)</label>
                        <input type="text" class="form-control" asp-for="CatName">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Ordering">Ordering</label>
                        <input type="text" class="form-control" asp-for="Ordering">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Ảnh đại diện</label>
                        <input type="file" name="fThumb" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published">
                                    <label for="Published"></label>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold">Title</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">SchemaMarkup</label>
                        <input type="text" class="form-control" asp-for="SchemaMarkup">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea asp-for="Description">
                    </textarea>
                </div>
            </div>
        </div>
    </div>
</form>
<hr />

@section CSS{
    <style>
        .ck.ck-editor__main > .ck-editor__editable {
            min-height: 200px !important;
        }
    </style>
}

@section Scripts{

    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/Adminassets/vendors/ckeditor/build/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Description'), {
                licenseKey: '',
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                console.warn('Build id: mxefwd8uabpg-nvqywtx4rvf5');
                console.error(error);
            });
    </script>
}

EMarket/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<EMarket.Models.Category>

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách category trang " + CurrentPage;

}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-action="Index">Quản lý Category</a>
            <span class="breadcrumb-item active">@ViewData["Title"]</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-sm-12 col-md-4">
                <a class="btn btn-success" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm</span>
                </a>
            </div>
        </div>
        <div class="table-responsive" style="overflow: hidden;">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên danh mục</th>
                        <th>Ordering</th>
                        <th>Trạng thái</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(_ => item.CatId)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => item.CatName)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => item.Ordering)
                            </td>
                            <td>
                                @if (item.Published == true)
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <div>Publish</div>
                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-danger badge-dot m-r-10"></div>
                                        <div>Non-Publish</div>
                                    </div>
                                }
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary m-r-5" asp-action="Details" asp-route-id="@item.CatId">Chi tiết</a>
                                <a class="btn btn-warning m-r-5" asp-action="Edit" asp-route-id="@item.CatId">Sửa</a>
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.CatId">Xóa</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            <div class="d-flex flex-row justify-content-center">
                <ul class="pagination">
                    @*Hoặc có thể dùng "page-container", sẽ khỏi overflow hidden *@
                    <pager class="pager-container"
                           list="@Model"
                           asp-area="Admin"
                           asp-controller="AdminCategories"
                           asp-action="Index"></pager>
                </ul>
            </div>
        </div>
    </div>
</div>