EMarket/Areas/Admin/Controllers/AdminTinDangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EMarket.Data;
using EMarket.Models;
using EMarket.Helper;
using PagedList.Core;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace EMarket.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminTinDangsController : Controller
    {
        private readonly dbMarketsContext _context;

        public AdminTinDangsController(dbMarketsContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminTinDangs
        public IActionResult Index(int? page)
        {
            var pageNumber = page == null || page < 0 ? 1 : page.Value;
            var pageSize = Utilities.PAGE_SIZE;
            var lst = _context.TinDangs
                                       .AsNoTracking()
                                       .OrderByDescending(c => c.CreatedDate);
            PagedList<TinDang> models = new PagedList<TinDang>(lst, pageNumber, pageSize);
            ViewBag.CurrentPage = pageNumber;
            return View(models);
        }

        // GET: Admin/AdminTinDangs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminTinDangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, IFormFile fThumb)
        {
            if (ModelState.IsValid)
            {
                if (fThumb != null)
                {
                    string extension = Path.GetExtension(fThumb.FileName);
                    string image = Utilities.SEOUrl(tinDang.Title) + extension;
                    tinDang.Thumb = await Utilities.UploadFile(fThumb, @"news", image.ToLower());
                }

                if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                tinDang.CreatedDate = DateTime.Now;

                _context.Add(tinDang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs.FindAsync(id);
            if (tinDang == null)
            {
                return NotFound();
            }
            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Scontents,Contents,Thumb,Published,Alias,CreatedDate,Author,AccountId,Tags,CatId,IsHot,IsNewfeed,MetaKey,MetaDesc,Views")] TinDang tinDang, IFormFile fThumb)
        {
            if (id != tinDang.PostId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    tinDang.Title = Utilities.ToTitleCase(tinDang.Title);
                    if (fThumb != null)
                    {
                        string extension = Path.GetExtension(fThumb.FileName);
                        string image = Utilities.SEOUrl(tinDang.Title) + extension;
                        tinDang.Thumb = await Utilities.UploadFile(fThumb, @"news", image.ToLower());
                    }

                    if (string.IsNullOrEmpty(tinDang.Thumb)) tinDang.Thumb = "default.jpg";
                    tinDang.Alias = Utilities.SEOUrl(tinDang.Title);
                    //tinDang.CreatedDate = DateTime.Now;

                    _context.Update(tinDang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TinDangExists(tinDang.PostId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tinDang);
        }

        // GET: Admin/AdminTinDangs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tinDang = await _context.TinDangs
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (tinDang == null)
            {
                return NotFound();
            }

            return View(tinDang);
        }

        // POST: Admin/AdminTinDangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tinDang = await _context.TinDangs.FindAsync(id);
            _context.TinDangs.Remove(tinDang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TinDangExists(int id)
        {
            return _context.TinDangs.Any(e => e.PostId == id);
        }
    }
}

EMarket/Areas/Admin/Views/AdminTinDangs/Create.cshtml
@model EMarket.Models.TinDang

@{
    ViewData["Title"] = "Thêm mới tin đăng";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminTinDangs" asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-success" type="submit">
                    <i class="anticon anticon-save"></i>
                    <span>Thêm</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Title">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Scontents">Mô tả ngắn</label>
                        <input type="text" class="form-control" asp-for="Scontents">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Ảnh đại diện</label>
                        <input type="file" name="fThumb" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published" checked="">
                                    <label for="Published"></label>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold"></label>
                        <input type="text" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea asp-for="Contents" class="form-control"></textarea>
                </div>
            </div>
        </div>
    </div>
</form>
<hr />

@section CSS{
    <style>
        .ck.ck-editor__main > .ck-editor__editable {
            min-height: 200px !important;
        }
    </style>
}

@section Scripts{

    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/Adminassets/vendors/ckeditor/build/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Contents'), {
                licenseKey: '',
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                console.warn('Build id: mxefwd8uabpg-nvqywtx4rvf5');
                console.error(error);
            });
    </script>
}

EMarket/Areas/Admin/Views/AdminTinDangs/Edit.cshtml
@model EMarket.Models.TinDang

@{
    ViewData["Title"] = "Chỉnh sửa tin đăng " + Model.PostId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<form asp-controller="AdminTinDangs" asp-route-id="@Model.PostId" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="PostId" />
    <input type="hidden" asp-for="Thumb" />
    <input type="hidden" asp-for="CreatedDate" />
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">

            </div>
            <div class="m-b-15">
                <button class="btn btn-success" type="submit">
                    <i class="anticon anticon-save"></i>
                    <span>Lưu</span>
                </button>
            </div>
        </div>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin SEO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
            </li>
        </ul>
    </div>
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Title">Tiêu đề</label>
                        <input type="text" class="form-control" asp-for="Title">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold" asp-for="Scontents">Mô tả ngắn</label>
                        <input class="form-control" asp-for="Scontents">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">Ảnh đại diện</label>
                        <input type="file" name="fThumb" class="form-control-file" asp-for="Thumb" />
                        <span asp-validation-for="Thumb" class="text-danger"></span>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="Published">
                                    <label for="Published"></label>
                                </div>
                                <label>Public</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsNewfeed">
                                    <label for="IsNewfeed"></label>
                                </div>
                                <label>IsNewfeed</label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="m-t-25">
                            <div class="form-group d-flex align-items-center">
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsHot">
                                    <label for="IsHot"></label>
                                </div>
                                <label>IsHot</label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-option">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaDesc</label>
                        <input type="text" class="form-control" asp-for="MetaDesc">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold">MetaKey</label>
                        <input type="text" class="form-control" asp-for="MetaKey">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-semibold"></label>
                        <input type="text" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="product-edit-description">
            <div class="card">
                <div class="card-body">
                    <textarea asp-for="Contents">
                    </textarea>
                </div>
            </div>
        </div>
    </div>
</form>
<hr />

@section CSS{
    <style>
        .ck.ck-editor__main > .ck-editor__editable {
            min-height: 200px !important;
        }
    </style>
}

@section Scripts{

    <script src="~/Adminassets/vendors/select2/select2.min.js"></script>
    <script src="~/Adminassets/vendors/quill/quill.min.js"></script>
    <script src="~/Adminassets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/Adminassets/vendors/ckeditor/build/ckeditor.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#Contents'), {
                licenseKey: '',
            })
            .then(editor => {
                window.editor = editor;
            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                console.warn('Build id: mxefwd8uabpg-nvqywtx4rvf5');
                console.error(error);
            });
    </script>
}

EMarket/Areas/Admin/Views/AdminTinDangs/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<EMarket.Models.TinDang>

@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";

    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Danh sách tin đăng trang " + CurrentPage;

}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <a class="breadcrumb-item" asp-action="Index">Quản lý tin đăng</a>
            <span class="breadcrumb-item active">@ViewData["Title"]</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-sm-12 col-md-4">
                <a class="btn btn-success" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm</span>
                </a>
            </div>
        </div>
        <div class="table-responsive" style="overflow: hidden;">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tiêu đề</th>
                        <th>Ngày viết</th>
                        <th>Public</th>
                        <th>IsHot</th>
                        <th>IsNewFeet</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(_ => item.PostId)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(_ => item.CreatedDate)
                            </td>
                            <td>
                                @if (item.Published == true)
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <div>Publish</div>
                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-danger badge-dot m-r-10"></div>
                                        <div>Non-Publish</div>
                                    </div>
                                }
                            </td>
                            <td>
                                @if (item.IsHot == true)
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <div>IsHot</div>
                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-danger badge-dot m-r-10"></div>

                                    </div>
                                }
                            </td>
                            <td>
                                @if (item.IsNewfeed == true)
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <div>IsNewwFeed</div>
                                    </div>
                                }
                                else
                                {
                                    <div class="d-flex align-items-center">
                                        <div class="badge badge-danger badge-dot m-r-10"></div>

                                    </div>
                                }
                            </td>
                            <td class="text-right">
                                <a class="btn btn-primary m-r-5" asp-action="Details" asp-route-id="@item.PostId">Chi tiết</a>
                                <a class="btn btn-warning m-r-5" asp-action="Edit" asp-route-id="@item.PostId">Sửa</a>
                                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.PostId">Xóa</a>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
            <div class="d-flex flex-row justify-content-center">
                <ul class="pagination">
                    <pager class="pager-container"
                           list="@Model"
                           asp-area="Admin"
                           asp-controller="AdminTinDangs"
                           asp-action="Index"></pager>
                </ul>
            </div>
        </div>
    </div>
</div>